name: 'Run tests'
description: 'Runs dotnet test using target frameworks appropriate for the current platform'
inputs:
  reset-script:
    description: 'pwsh expression to be run between test runs to reset infrastructure, if required'
    required: false
  path:
    description: The path to specify for `dotnet test`. Defaults to `src` to assume a single sln file in the src directory.
    required: false
    default: src
runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup
      shell: pwsh
      env:
        RESET_SCRIPT: ${{ inputs.reset-script }}
      run: |
        $script = $Env:RESET_SCRIPT
        if (-not ([string]::IsNullOrEmpty($script))) {
          echo $Env:RESET_SCRIPT > ${{ github.action_path }}/reset-script.ps1
          echo "::set-output name=has-reset-script::true"
        }
    - name: Run tests
      shell: pwsh
      env:
        RESET_SCRIPT: ${{ github.action_path }}/reset-script.ps1
        HAS_RESET_SCRIPT: ${{ steps.setup.outputs.has-reset-script }}
        PATH_PARAMETER: ${{ inputs.path }}
      run: ${{ github.action_path }}/run-tests.ps1