name: 'Run tests'
description: 'Runs dotnet test using target frameworks appropriate for the current platform'
inputs:
  between-runs:  # id of input
    description: 'pwsh expression to be run between test runs'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run-tests.ps1
      shell: pwsh