name: 'Run tests'
description: 'Runs dotnet test using target frameworks appropriate for the current platform'
inputs:
  reset-script:
    description: 'pwsh expression to be run between test runs to reset infrastructure, if required'
    required: false
  framework:
    description: Specifies the target framework to run tests for
    required: false
  report-warnings:
    description: Specifies whether to report warnings for tests that have neither failed nor succeeded (i.e. skipped or inconclusive)
    required: false
  target-platform:
    description: Specifies the RunConfiguration.TargetPlatform for dotnet test. Defaults to 'x64'.
    required: false
    default: x64
  filter:
    description: Specifies the filter, if any, to use when running the tests
    required: false
runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup
      shell: pwsh
      env:
        RESET_SCRIPT: ${{ inputs.reset-script }}
      run: |
        $script = $Env:RESET_SCRIPT
        if (-not ([string]::IsNullOrEmpty($script))) {
          echo $Env:RESET_SCRIPT > ${{ github.action_path }}/reset-script.ps1
          echo "has-reset-script=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
    - name: Run tests
      shell: pwsh
      env:
        RESET_SCRIPT: ${{ github.action_path }}/reset-script.ps1
        HAS_RESET_SCRIPT: ${{ steps.setup.outputs.has-reset-script }}
        EXPLICIT_TEST_FRAMEWORK: ${{ inputs.framework }}
        REPORT_WARNINGS: ${{ inputs.report-warnings }}
        TARGET_PLATFORM: ${{ inputs.target-platform }}
        FILTER: ${{ inputs.filter }}        
      run: ${{ github.action_path }}/run-tests.ps1
